default:
#	clang++ *.cpp ../lib/*.cpp  -lpthread  -lglut -lGLU -lGL -o main -std=c++11
	clang++ *.cpp ../lib/*.cpp -framework GLUT -framework OpenGL -framework Cocoa -o main -Wno-deprecated -std=c++11
